Update debug to fix ReDoS vulnerability
sailshq/machinepack-mysql pull request #10
Opened 2018-03-10 08:25 UTC by fenichelar

Vulnerability: Regular Expression Denial of Service
Package Name: debug
CVSS: 3.7 (Low)
Installed: 2.2.0
Vulnerable: <= 2.6.8 || >= 3.0.0 <= 3.0.1
Patched: >= 2.6.9 < 3.0.0 || >= 3.1.0
Path: sails-mysql@1.0.0-17 > machinepack-mysql@3.0.1 > debug@2.2.0
More Info: https://nodesecurity.io/advisories/534

https://github.com/balderdashy/sails/issues/4319

2018-03-25 21:00 UTC, mikermcneil requested changes

2018-03-25 21:00 UTC, mikermcneil commented on package.json
> +    "debug": "^2.6.9",
@fenichelar In the Sails project, we pin the SVRs of all dependencies that are not maintained by our core team.  Would you mind changing that to `2.6.9`, and also updating https://github.com/sailshq/roadstead/blob/2843d86e075e0cdec34ac8d20b72ad343b88c085/constants/verified-releases.type.js#L34 ?

2018-03-25 22:26 UTC, fenichelar commented
@mikermcneil Done here. And done in roadstead: https://github.com/sailshq/roadstead/pull/1

2018-04-03 15:20 UTC, fenichelar commented
@mikermcneil Let me know if there is anything else that needs to be changed.

2018-04-09 01:39 UTC, merged

2018-04-09 01:40 UTC, mikermcneil commented
@fenichelar thanks!

2018-04-23 20:02 UTC, fenichelar commented
Any word on when this can be released? Build tools are crying.

2018-05-02 16:08 UTC, fenichelar commented
@mikermcneil It looks like the version number in `package.json` was bumped but the release is not available on npm, is there an issue preventing this from being published? Thanks!